services:
  lazyfp:
    build: .
    # image: ghcr.io/kiss2u/lazyfp:latest
    container_name: lazyfp
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./fp:/app/fp
    environment:
      - PYTHONUNBUFFERED=1
